name: PagerGuild

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache SQLite Database
        uses: actions/cache@v3
        with:
          path: |
            pagerguild.db
          key: sqlite-cache-key-v2

      - name: Review migrations
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run \
            -e GITHUB_TOKEN \
            -e OPENAI_API_KEY \
            -e GITHUB_REPOSITORY_OWNER -e GITHUB_REPOSITORY -e GITHUB_REF -e GITHUB_EVENT_NAME \
            -v $PWD:/src/ \
            pagerguild/pagerguild:latest scan
